// Lospia / Aslı Filinta Operasyon — Haftanın Sözü havuzu.
//
// İki katmanlı havuz. Veri statik tutulur — production DB'ye migration
// YAPILMAZ; içerik yalnızca burada, typecheck ile korunan bir TypeScript
// sabiti olarak yaşar.
//
//   quote_001 … quote_100  Gemini Deep Research derlemesi (bkz. gemini.md).
//                          Neredeyse tamamı UI DIŞINDADIR: bir bölümü
//                          quote-aggregator kaynaklı, 47 tanesi de kurum içinde
//                          yazılmış özgün aforizmaydı ve 08.09.2026'da
//                          reddedildi ("bu ne saçma mantıksız söz").
//   quote_101 …            10.09.2026'da eklenen, atfı BİRİNCİL KAYNAKTAN
//                          doğrulanmış moda tasarımcısı sözleri. UI'yı bunlar
//                          taşır.
//
// Editoryal güvenlik katmanı (sourceConfidence / approvedForUi):
//   - "original" → Filinta Metodolojisi'nin kendi özgün atölye notları. Kesin
//                  tarihî atıf yapılmaz; "Atölye Notu" (tezgâh sesi) ve
//                  "Filinta Metodolojisi" (yöntem sesi) kolektif sesleri
//                  kullanılır. UI'da kullanılır.
//   - "high"     → resmî marka / müze / vakıf / akademik yayın kaynaklı doğrulanmış
//                  sözler, UI'da kullanılır (approvedForUi: true).
//   - "medium"   → Wikipedia/Wikiquote, dergi/haber ve kesin atfı doğrulanamayan
//                  tarihî sözler. İlk aşamada UI dışında (approvedForUi: false).
//   - "low"      → quote-aggregator / blog kaynaklı, doğrulaması zayıf sözler.
//                  UI dışında (approvedForUi: false).
//
// TON KURALI (AF_MD marka dosyası, 2026-08-29): özgün notlar bir işi TARİF
// eder, kimseye nasihat etmez. Somut olan yazılır — bir el hareketi, bir
// malzeme, bir sıra, bir sayı. Soyut sıfat yığını ("kadim", "zamansız",
// "eşsiz", "sessiz imza", "ruh", "pusula", "köprü") ve motivasyon cümlesi
// ("her sabah üzerine titre") YASAK. Cümle kısa; Türkçenin kendi ritmiyle
// yazılır, İngilizceden çevrilmez. Marka dosyasındaki doğrulanmış sayı, yer
// ve proje adları (kooperatif isimleri, adetler, yıllar) bu havuza GİRMEZ —
// buradan yalnızca ton ve mantık alınır.
//
// UI yalnızca APPROVED_WEEKLY_QUOTES üzerinden döner; söz seçimi deterministiktir
// (haftalık rotasyon), random DEĞİLDİR.

export type WeeklyQuote = {
  id: string;
  weekIndex: number;
  quoteTr: string;
  quoteOriginal?: string | null;
  author: string;
  authorRole: string;
  category: string;
  theme: string;
  sourceType:
    | "verified_quote"
    | "public_domain_quote"
    | "translated_quote"
    | "inspired_original";
  sourceUrl?: string | null;
  usageRecommendation: "use" | "use_as_translation" | "use_as_inspired";
  brandFitScore: number;
  uiDisplaySuggestion: string;
  sourceConfidence: "high" | "medium" | "low" | "original";
  approvedForUi: boolean;
};

export const WEEKLY_QUOTES: WeeklyQuote[] = [
  {
    id: "quote_001",
    weekIndex: 1,
    quoteTr: "Sadelik, tüm gerçek zarafetin anahtarıdır.",
    quoteOriginal: "Simplicity is the keynote of all true elegance.",
    author: "Coco Chanel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "zarafet",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Coco_Chanel",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_002",
    weekIndex: 2,
    quoteTr: "Moda mimaridir; her şey oranlarla ilgilidir.",
    quoteOriginal: "Fashion is architecture: it is a matter of proportions.",
    author: "Coco Chanel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Coco_Chanel",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_003",
    weekIndex: 3,
    quoteTr: "Çok çalışmak her zaman benim tek kurtuluşum oldu.",
    quoteOriginal: "Hard work has always been my salvation.",
    author: "Coco Chanel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "emek",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Coco_Chanel",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_004",
    weekIndex: 4,
    quoteTr: "Detaylar en az esas olan kadar önemlidir. Yetersiz kaldıklarında tüm tasarımı yok ederler.",
    quoteOriginal: "The detail is as important as the essential is. When it is inadequate, it destroys the whole outfit.",
    author: "Christian Dior",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://www.pairfum.com/christian-dior-his-50-x-most-memorable-quotes/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_005",
    weekIndex: 5,
    quoteTr: "Makinelerin çağında dikişçilik, insani, kişisel ve taklit edilemez olanın son sığınaklarından biridir.",
    quoteOriginal: "In a machine age, dressmaking is one of the last refuges of the human, the personal, the inimitable.",
    author: "Christian Dior",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Christian_Dior",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_006",
    weekIndex: 6,
    quoteTr: "Robert Piguet bana gerçek zarafetin kaynağı olan sadeliğin erdemlerini öğretti.",
    quoteOriginal: "Robert Piguet taught me the virtues of simplicity through which true elegance must come.",
    author: "Christian Dior",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Christian_Dior",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_007",
    weekIndex: 7,
    quoteTr: "Moda geçer, stil kalıcıdır.",
    quoteOriginal: "Fashions fade, style is eternal.",
    author: "Yves Saint Laurent",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "miras",
    sourceType: "verified_quote",
    sourceUrl: "https://museeyslparis.com/en/biography/premier-smoking",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    // YSL "moda geçer stil kalır" — havuzun en aşınmış klişesi; küratör de aynı sözü eledi.
    approvedForUi: false,
  },
  {
    id: "quote_008",
    weekIndex: 8,
    quoteTr: "Kendimi kadınların hizmetine sunmak, geçen yüzyıldaki büyük özgürleşme hareketlerinde onlara eşlik etmek istedim.",
    quoteOriginal: "I wanted to put myself at the service of women. To accompany them in the great movement for liberation.",
    author: "Yves Saint Laurent",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kadın emeği",
    sourceType: "translated_quote",
    sourceUrl: "https://gloss-newyork.com/fashion-ready-to-wear/saint-laurent/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_009",
    weekIndex: 9,
    quoteTr: "Kuralları yıkmak için önce onlara hâkim olmalısınız. Buradayım; kuralları yıkmak ama geleneği korumak için.",
    quoteOriginal: "You've got to know the rules to break them. That's what I'm here for, to demolish the rules but to keep the tradition.",
    author: "Alexander McQueen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/alexander-mcqueen-an-introduction",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    // McQueen "kuralları yıkmak" — yıpranmış aforizma; yerine aynı yazarın atölye sözleri geldi.
    approvedForUi: false,
  },
  {
    id: "quote_010",
    weekIndex: 10,
    quoteTr: "Moda bir kaçış ve özgürleşme alanı olmalıdır, bir hapishane değil.",
    quoteOriginal: "Fashion should be a form of escapism, and not a form of imprisonment.",
    author: "Alexander McQueen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://www.hockerty.com/en-us/blog/fashion-quotes-men",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_011",
    weekIndex: 11,
    quoteTr: "Daha az satın alın, iyi seçin, kalıcı kılın.",
    quoteOriginal: "Buy less, choose well, make it last.",
    author: "Vivienne Westwood",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.viviennewestwood.com/sustainability/make-it-last.html",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_012",
    weekIndex: 12,
    quoteTr: "Sadece moda yapmak istemedim, tasarımlarım aracılığıyla bir hikaye anlatmak istedim.",
    quoteOriginal: "I didn't want to just do fashion, I wanted to tell a story through my designs.",
    author: "Vivienne Westwood",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "miras",
    sourceType: "translated_quote",
    sourceUrl: "https://www.designville.eu/blog/buy-less-choose-well-thank-you-vivienne-westwood",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_013",
    weekIndex: 13,
    quoteTr: "Zarafet göze batmak değil, akılda kalmaktır.",
    quoteOriginal: "Elegance is not standing out, but being remembered.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "zarafet",
    sourceType: "verified_quote",
    sourceUrl: "https://www.standard.co.uk/lifestyle/fashion/giorgio-armani-dies-obituary-life-of-legendary-italian-designer-b1246059.html",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_014",
    weekIndex: 14,
    quoteTr: "Alanınızda en iyisi olmak büyük bir hırstır; disiplin ve muazzam miktarda çaba gerektirir.",
    quoteOriginal: "To be the best in your field is a great ambition, and requires discipline and a huge amount of effort.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://www.azquotes.com/author/529-Giorgio_Armani?p=3",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_015",
    weekIndex: 15,
    quoteTr: "Ben tablodaki bir kadını değil; yaşayan, üreten ve çalışan kadını giydirmek istedim.",
    quoteOriginal: "I wanted to dress the woman who lives and works, not the woman in a painting.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kadın emeği",
    sourceType: "verified_quote",
    sourceUrl: "https://www.azquotes.com/author/529-Giorgio_Armani?p=3",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_016",
    weekIndex: 16,
    quoteTr: "Yaratım ile iş dünyası arasında fark yoktur. Bir şirketin işleyişi de yaratıcı, yenilikçi ve dönüştürücü olmalıdır.",
    quoteOriginal: "There is no difference between creation and business. The business aspect of a company has to be creative, innovative, transformative.",
    author: "Rei Kawakubo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://successstory.com/inspiration/successstory-quotes-rei-kawakubo-part-01",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_017",
    weekIndex: 17,
    quoteTr: "Yaratıcılık her şeyi ileriye taşır. Yeni bir şey olmadan ilerleme olmaz. Yaratım, yeniliktir.",
    quoteOriginal: "Creation takes things forward. Without anything new, there is no progress. Creation equals new.",
    author: "Rei Kawakubo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/quote/1647328/Rei-Kawakubo-Creation-takes-things-forward-Without-anything-new-there-is-no-progress",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_018",
    weekIndex: 18,
    quoteTr: "Çünkü temel insani mesele, insanların değişimden korkmasıdır.",
    quoteOriginal: "Because the fundamental human problem is that people are afraid of change.",
    author: "Rei Kawakubo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/rei-kawakubo-quotes",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_019",
    weekIndex: 19,
    quoteTr: "Tasarım soyut bir felsefe için değil, doğrudan yaşam içindir.",
    quoteOriginal: "Design is not for philosophy, it's for life.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Issey_Miyake",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_020",
    weekIndex: 20,
    quoteTr: "En çok insan formuyla ilgileniyorum. Giysi, yaşayan insana en yakın olan şeydir.",
    quoteOriginal: "I am most interested in people and the human form. Clothing is closest to all humans.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Issey_Miyake",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_021",
    weekIndex: 21,
    quoteTr: "Beni ilgilendiren kumaşın teknolojisi, her şeye sıfırdan ve malzemeden başlamaktır.",
    quoteOriginal: "The technology of fabrics is what interests me. Making things from scratch.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Issey_Miyake",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_022",
    weekIndex: 22,
    quoteTr: "Benim için moda, bedene en yakın sanat formudur. Kim olduğumuzun en yalın ifadesidir.",
    quoteOriginal: "For me, fashion is an art form that is very close to the body. It is the closest expression of who we are.",
    author: "Iris van Herpen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Iris_van_Herpen",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_023",
    weekIndex: 23,
    quoteTr: "El işçiliği ve dijital zanaatkarlık yan yana var olabilir, birbirini besleyebilir; ayrılmamalıdırlar.",
    quoteOriginal: "Handmaking and digital craftsmanship can coexist and feed each other. They shouldn't be separated.",
    author: "Iris van Herpen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Iris_van_Herpen",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_024",
    weekIndex: 24,
    quoteTr: "Elleriniz kültürdür. Ruhunuz parmak uçlarınızdan dışarı süzülür. Moda, zanaatkarlığın son kalesidir.",
    quoteOriginal: "Your hands are culture. Your soul comes out at the tips of your fingers. Fashion is the last business of craftsmanship.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://www.sleek-mag.com/article/notes-and-quotes-from-yohji-yamamoto/",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_025",
    weekIndex: 25,
    quoteTr: "Kusursuzluğun çirkin olduğunu düşünüyorum. İnsan elinden çıkan şeylerde izler, hatalar ve düzensizlikler görmek isterim.",
    quoteOriginal: "I think perfection is ugly. Somewhere in the things humans make, I want to see scars, failure, disorder, distortion.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "emek",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Yohji_Yamamoto",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_026",
    weekIndex: 26,
    quoteTr: "Lütfen giysileri israf etmeyin! Tasarımla bir aşk macerası yaşayın ve o giysiyle birlikte uzun yıllar yaşayın.",
    quoteOriginal: "Please, don't waste clothing! Fall in love and live with this piece of clothing.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.sleek-mag.com/article/notes-and-quotes-from-yohji-yamamoto/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_027",
    weekIndex: 27,
    quoteTr: "Ben kadın olmaktan gurur duyan, kadınlığını yaşayan tüm güçlü kadınlar için tasarlıyorum.",
    quoteOriginal: "I design for the woman who loves being a woman.",
    author: "Diane von Furstenberg",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kadın emeği",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Diane_von_Furstenberg",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_028",
    weekIndex: 28,
    quoteTr: "Hedefim sade, rahat ve zarif bir elbise yaratmaktı; kadının kendi gücünü ortaya çıkaran bir tasarım.",
    quoteOriginal: "My goal was to create a dress that was simple, comfortable, and elegant.",
    author: "Diane von Furstenberg",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Diane_von_Furstenberg",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_029",
    weekIndex: 29,
    quoteTr: "En sürdürülebilir tasarım, insanların atmak istemeyeceği kalıcı parçalar üretmektir.",
    quoteOriginal: "One of the most sustainable things you can do as a designer is to create pieces that people want and won't want to throw away.",
    author: "Stella McCartney",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.stellamccartney.com/on/demandware.static/-/Library-Sites-StellaMcCartneySharedLibrary/default/dwce449f0d/report/EcoImpact_2021_CM_FINAL.pdf",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_030",
    weekIndex: 30,
    quoteTr: "İnsan olarak kurduğumuz her tekil etkileşimin ve aldığımız her kararın gezegen üzerinde bir etkisi vardır.",
    quoteOriginal: "Every single interaction that we have as humans can have an impact on the planet.",
    author: "Stella McCartney",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.dezeen.com/2018/07/10/stella-mccartney-interview-sustainable-design/",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_031",
    weekIndex: 31,
    quoteTr: "Sürdürülebilir moda bir akım değil, hepimizin üstlenmesi gereken bir sorumluluktur.",
    quoteOriginal: "Sustainable fashion is not a trend, it's a responsibility.",
    author: "Stella McCartney",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://ecoswap.uk/top-10-sustainable-fashion-quotes/",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_032",
    weekIndex: 32,
    quoteTr: "Bir şeyi derinlemesine yapabilmenin tek yolu çok çalışmaktır.",
    quoteOriginal: "The only way to do something in depth is to work hard.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/miuccia-prada-quotes",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_033",
    weekIndex: 33,
    quoteTr: "Ben gerçekten uzun ömürlü olacak, zamanın ötesinde ve kalıcı giysiler yapmak istiyorum.",
    quoteOriginal: "I really want to make clothes that will last a long time.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.bookey.app/quote-author/miuccia-prada",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_034",
    weekIndex: 34,
    quoteTr: "Ne giydiğiniz, kendinizi dünyaya nasıl sunduğunuzdur. Özellikle bugün, iletişim bu kadar hızlıyken; moda anlık bir dildir.",
    quoteOriginal: "What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "zarafet",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/miuccia-prada-quotes",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_035",
    weekIndex: 35,
    quoteTr: "Tasarım; konfor ile lüksü, pratik olan ile arzulananı dengeleme mücadelesidir.",
    quoteOriginal: "Design is a constant challenge to balance comfort with luxe, the practical with the desirable.",
    author: "Donna Karan",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Donna_Karan",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_036",
    weekIndex: 36,
    quoteTr: "Hayatınızda yararlı olduğunu bilmediğiniz ya da güzel olduğuna inanmadığınız hiçbir şeye yer vermeyin.",
    quoteOriginal: "Have nothing in your houses that you do not know to be useful or believe to be beautiful.",
    author: "William Morris",
    authorRole: "Tasarımcı ve zanaat kuramcısı",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/William_Morris",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_037",
    weekIndex: 37,
    quoteTr: "Güzel bir el işçiliği, mutlu bir kalbin ve disiplinli bir zihnin doğal ifadesidir.",
    quoteOriginal: "Beautiful handwork is the natural expression of a joyful heart and a disciplined mind.",
    author: "William Morris",
    authorRole: "Tasarımcı ve zanaat kuramcısı",
    category: "craft",
    theme: "emek",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/William_Morris",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_038",
    weekIndex: 38,
    quoteTr: "Daha az, ama daha iyi.",
    quoteOriginal: "Weniger, aber besser",
    author: "Dieter Rams",
    authorRole: "Endüstriyel tasarımcı",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Dieter_Rams",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_039",
    weekIndex: 39,
    quoteTr: "İyi tasarım son detayına kadar titizdir. Süreçteki özen ve doğruluk, insana duyulan saygının göstergesidir.",
    quoteOriginal: "Good design is thorough down to the last detail. Care and accuracy in the design process show respect towards the consumer.",
    author: "Dieter Rams",
    authorRole: "Endüstriyel tasarımcı",
    category: "craft",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://designmuseum.org/discover-design/all-stories/what-is-good-design-a-quick-look-at-dieter-rams-ten-principles",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "high",
    // Dieter Rams — endüstriyel tasarımcı; havuz moda/tekstil sesine indirgendi.
    approvedForUi: false,
  },
  {
    id: "quote_040",
    weekIndex: 40,
    quoteTr: "İyi tasarım çevre dostudur. Tasarım, ürünün yaşam döngüsü boyunca kaynakları korumaya ve kirliliği azaltmaya hizmet etmelidir.",
    quoteOriginal: "Good design is environmentally friendly. Design makes an important contribution to the preservation of the environment.",
    author: "Dieter Rams",
    authorRole: "Endüstriyel tasarımcı",
    category: "craft",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://designmuseum.org/discover-design/all-stories/what-is-good-design-a-quick-look-at-dieter-rams-ten-principles",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "high",
    // Dieter Rams — endüstriyel tasarımcı; havuz moda/tekstil sesine indirgendi.
    approvedForUi: false,
  },
  {
    id: "quote_041",
    weekIndex: 41,
    quoteTr: "Detaylar sadece detay değildir; tasarımı oluşturan şeyin ta kendisidir.",
    quoteOriginal: "The details are not the details. They make the design.",
    author: "Charles Eames",
    authorRole: "Tasarımcı ve mimar",
    category: "craft",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Charles_and_Ray_Eames",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_042",
    weekIndex: 42,
    quoteTr: "Tasarım, unsurları belirli bir amaca en iyi hizmet edecek şekilde düzenleme planıdır.",
    quoteOriginal: "Design is a plan for arranging elements in such a way as best to accomplish a particular purpose.",
    author: "Charles Eames",
    authorRole: "Tasarımcı ve mimar",
    category: "craft",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Charles_and_Ray_Eames",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_043",
    weekIndex: 43,
    quoteTr: "İşlevsel olan, sadece iyi görünenden daha iyidir. Görünüm değişebilir ama işleyen şey her zaman işler.",
    quoteOriginal: "What works is better than what looks good. The looks good can change, but what works works.",
    author: "Ray Eames",
    authorRole: "Tasarımcı ve sanatçı",
    category: "craft",
    theme: "operasyon disiplini",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Charles_and_Ray_Eames",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_044",
    weekIndex: 44,
    quoteTr: "Karışık hale getirmek kolaydır, basitleştirmek zordur. Herkes karmaşıklaştırabilir, sadece az sayıda kişi basitleştirebilir.",
    quoteOriginal: "To complicate is easy, to simplify is difficult... Everyone is able to complicate. Few are able to simplify.",
    author: "Bruno Munari",
    authorRole: "Tasarımcı ve yazar",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Bruno_Munari",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_045",
    weekIndex: 45,
    quoteTr: "Nesneler özenle ve akılla yapıldığında, güzellikleri doğrudan işlevselliklerinden dışarı sızar.",
    quoteOriginal: "When objects are made with care and intelligence, their beauty shines through their functionality.",
    author: "Bruno Munari",
    authorRole: "Tasarımcı ve yazar",
    category: "craft",
    theme: "estetik",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Bruno_Munari",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_046",
    weekIndex: 46,
    quoteTr: "Bir parçayı tarif ederken sıfat kullanmayız: ölçü, renk, malzeme. Gerisi lafta kalır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sadelik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_047",
    weekIndex: 47,
    quoteTr: "Çizgi, yürüyüşe çıkmış bir noktadır.",
    quoteOriginal: "A line is a dot that went for a walk.",
    author: "Paul Klee",
    authorRole: "Ressam ve Bauhaus kuramcısı",
    category: "craft",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Paul_Klee",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_048",
    weekIndex: 48,
    quoteTr: "Sanat görüneni yeniden üretmez; aksine, insan gözü için onu görünür kılar.",
    quoteOriginal: "Art does not reproduce the visible; rather, it makes visible.",
    author: "Paul Klee",
    authorRole: "Ressam ve Bauhaus kuramcısı",
    category: "craft",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Paul_Klee",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_049",
    weekIndex: 49,
    quoteTr: "Sanatın herhangi bir dalında kendi dünyanı yaratabilmek, her şeyden önce cesaret gerektirir.",
    quoteOriginal: "To create one's world in any of the arts takes courage.",
    author: "Georgia O'Keeffe",
    authorRole: "Modernist ressam",
    category: "craft",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Georgia_O%27Keeffe",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_050",
    weekIndex: 50,
    quoteTr: "Malzeme bir iletişim aracıdır. Ona hükmetmek yerine onu dinlemek bizi gerçekten aktif ve yaratıcı kılar.",
    quoteOriginal: "The material is a means of communication. Listening to it, not dominating it, makes us truly active.",
    author: "Anni Albers",
    authorRole: "Tekstil ve dokuma sanatçısı",
    category: "craft",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://www.albersfoundation.org/alberses/teaching/anni-albers/material-as-metaphor",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_051",
    weekIndex: 51,
    quoteTr: "Yaparım, bozarım, yeniden yaparım. Bu döngü, zanaatın ve zihnin kendini iyileştirme biçimidir.",
    quoteOriginal: "I do, I undo, I redo. This is the process of making and repairing.",
    author: "Louise Bourgeois",
    authorRole: "Heykeltıraş ve sanatçı",
    category: "craft",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://www.euppublishing.com/doi/10.3366/jobs.2023.0389",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    // Louise Bourgeois — heykeltıraş; havuz moda/tekstil sesine indirgendi.
    approvedForUi: false,
  },
  {
    id: "quote_052",
    weekIndex: 52,
    quoteTr: "İplik; zamanın akışını, dokuyan bir annenin dikişini, bağların hassasiyetini ve hafızaya tutunmayı temsil eder.",
    quoteOriginal: "The thread represents the unspooling of time, the sewing of the mother-weaver, the fragility of relationships and linkage to memory.",
    author: "Louise Bourgeois",
    authorRole: "Heykeltıraş ve sanatçı",
    category: "craft",
    theme: "miras",
    sourceType: "translated_quote",
    sourceUrl: "https://sculpture.org/blogpost/1860273/350131/Louise-Bourgeois-Conscious-and-Unconscious",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: false,
  },
  {
    id: "quote_053",
    weekIndex: 53,
    quoteTr: "Ölçüyü iki kez alırız, kumaşı bir kez keseriz.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_054",
    weekIndex: 54,
    quoteTr: "Vicdanlı bir tasarımcı bizzat tasarlamaz; aksine, nesneye kendi kendini var etme ve tasarlama şansı verir.",
    quoteOriginal: "The conscientious designer does not himself design at all but rather give the object-to-be a chance to design itself.",
    author: "Anni Albers",
    authorRole: "Tekstil ve dokuma sanatçısı",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.tate.org.uk/whats-on/tate-modern/anni-albers/seven-life-hacks-anni-albers",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: false,
  },
  {
    id: "quote_055",
    weekIndex: 55,
    quoteTr: "Yavaşlık ve deneysellik, zanaatta gerçek yeniliğin ve kalıcı kalitenin en sağlam temelleridir.",
    quoteOriginal: "Slowness and experimentation are the foundations of true innovation and lasting quality in craft.",
    author: "Anni Albers",
    authorRole: "Tekstil ve dokuma sanatçısı",
    category: "craft",
    theme: "sabır",
    sourceType: "translated_quote",
    sourceUrl: "https://www.tate.org.uk/whats-on/tate-modern/anni-albers/seven-life-hacks-anni-albers",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_056",
    weekIndex: 56,
    quoteTr: "Sökmek ayıp değil; geç sökmek pahalı.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_057",
    weekIndex: 57,
    quoteTr: "El işinde hız yoktur, tekrar vardır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_058",
    weekIndex: 58,
    quoteTr: "Bir parçanın fiyatı kumaşta değil, ona harcanan günde belli olur.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_059",
    weekIndex: 59,
    quoteTr: "Zor olan dikmek değil; ikinci parçayı birincisiyle aynı dikmek.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_060",
    weekIndex: 60,
    quoteTr: "Kayıt tutulmayan iş yapılmamış sayılır. Kim, ne, ne zaman — üç satır yeter.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_061",
    weekIndex: 61,
    quoteTr: "Ustaya sorulan soru, iki gün sonra sökülen dikişten kısadır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_062",
    weekIndex: 62,
    quoteTr: "İşi bölüşmek, sorumluluğu bölmek değildir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_063",
    weekIndex: 63,
    quoteTr: "Bir işi üç cümlede anlatamıyorsak, iş daha netleşmemiştir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sadelik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_064",
    weekIndex: 64,
    quoteTr: "Fikir tezgâha inmediyse hâlâ fikirdir.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_065",
    weekIndex: 65,
    quoteTr: "İlmek atılmadan önce düşünülür, atıldıktan sonra sökülür.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_066",
    weekIndex: 66,
    quoteTr: "Numune onaylanmadan kesim başlamaz; sıra bozulunca iş değil kumaş gider.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_067",
    weekIndex: 67,
    quoteTr: "Yeni bir teknik bir günde öğrenilir, her gün tekrar edilerek elde kalır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_068",
    weekIndex: 68,
    quoteTr: "Yarım bırakılan iş, bir dahaki sefere baştan başlar.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_069",
    weekIndex: 69,
    quoteTr: "Astarın içi dışı kadar temiz olur. Kimse görmüyor diye başka türlü dikilmez.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_070",
    weekIndex: 70,
    quoteTr: "Gün sonunda tezgâh toplanır; ertesi sabah dağınıklıktan başlamak işten çalar.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "disiplin",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_071",
    weekIndex: 71,
    quoteTr: "Elde iş varken yeni iş almak ikisini de geciktirir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_072",
    weekIndex: 72,
    quoteTr: "Son ütü, ilk dikişi görünür kılar.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "estetik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_073",
    weekIndex: 73,
    quoteTr: "Tarih tahmin değildir. Tahminse öyle söylenir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "disiplin",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_074",
    weekIndex: 74,
    quoteTr: "Bir işin sahibi varsa iş yürür. Herkesin işi kimsenin işidir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_075",
    weekIndex: 75,
    quoteTr: "Kâğıtta denenmeyen kalıp kumaşta denenir; kumaş geri gelmez.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_076",
    weekIndex: 76,
    quoteTr: "Bir teknik, onu gösterecek biri kaldığı sürece yaşar.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "miras",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_077",
    weekIndex: 77,
    quoteTr: "Bir parçanın kaç kişinin elinden geçtiğini bilmeden fiyatını konuşmayız.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "kadın emeği",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_078",
    weekIndex: 78,
    quoteTr: "Ne kadar sade görünüyorsa, o kadar çok kez sökülmüştür.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "zarafet",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_079",
    weekIndex: 79,
    quoteTr: "Kumaş biterse o parça biter. Az üretmek eksiklik değil, karar.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_080",
    weekIndex: 80,
    quoteTr: "İlk parça yavaş çıkar. Yavaş çıkmazsa ikincisi hiç çıkmaz.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_081",
    weekIndex: 81,
    quoteTr: "Artan kumaş çöp değil, bir sonraki parçanın başlangıcıdır.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_082",
    weekIndex: 82,
    quoteTr: "Ustalık, hangi dikişin sökülmesi gerektiğini ilk bakışta görmektir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_083",
    weekIndex: 83,
    quoteTr: "Bir işi devrederken elindeki her şeyi devret; yarısı sende kalırsa iş de sende kalır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "kadın emeği",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_084",
    weekIndex: 84,
    quoteTr: "İki kişi aynı işi yapıyorsa biri boşa çalışıyor. Sabah on dakika bunu çözer.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_085",
    weekIndex: 85,
    quoteTr: "Elimizde ne varsa onunla başlarız; olmayanı beklemek üretim değil, erteleme.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_086",
    weekIndex: 86,
    quoteTr: "Sabah listesi üç satırdır: ismi, işi, tarihi.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sadelik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_087",
    weekIndex: 87,
    quoteTr: "Bir dikiş sökülüyorsa suçlusu aranmaz, sebebi yazılır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_088",
    weekIndex: 88,
    quoteTr: "Desen bir yerden geliyorsa, o yerin adı da beraber yazılır.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "miras",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_089",
    weekIndex: 89,
    quoteTr: "Karar çıkmayan toplantı ertesi hafta yeniden yapılır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_090",
    weekIndex: 90,
    quoteTr: "Renk kartına güneşte de bakarız; masa lambası herkesi yanıltır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "estetik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_091",
    weekIndex: 91,
    quoteTr: "Eskiyen parça atılmaz, sökülür. Sökülen her parça bir sonrakine ölçü verir.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_092",
    weekIndex: 92,
    quoteTr: "Bir tarih değişiyorsa sebebiyle birlikte yazılır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "disiplin",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_093",
    weekIndex: 93,
    quoteTr: "Kumaşa istediğimizi değil, kaldırdığını yaptırırız.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_094",
    weekIndex: 94,
    quoteTr: "Provada görülen, üretimde görülecek olandır. Provayı atlamak işi iki kez yapmaktır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_095",
    weekIndex: 95,
    quoteTr: "Öğrenilen teknik anlatılmazsa bizde kalır; bizde kalan teknik biter.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "miras",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_096",
    weekIndex: 96,
    quoteTr: "Elin bildiği kâğıda geçmezse, tezgâh boşaldığında o bilgi de gider.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "kadın emeği",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_097",
    weekIndex: 97,
    quoteTr: "Numuneye elle dokunmadan onay verilmez; ekranda kumaşın tuşesi yok.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_098",
    weekIndex: 98,
    quoteTr: "Bir işe başlamadan sonunu yazarız: kaç el, kaç gün, ne kadar kumaş.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_099",
    weekIndex: 99,
    quoteTr: "İyi iş, ertesi sabah utanmadan bakabildiğin iştir.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "zarafet",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  {
    id: "quote_100",
    weekIndex: 100,
    quoteTr: "Yeni bir şey almadan önce elimizdekine bakarız; cevap çoğu zaman oradadır.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: false,
  },
  // -------------------------------------------------------------------------
  // 2026-09-10 — DOĞRULANMIŞ MODA TASARIMCISI SÖZLERİ (quote_101 … quote_143)
  //
  //   "Haftanın sözü geri gelsin, profesyonelce Aslı Hanım'ın tarzında olmalı.
  //    Anlamlı ve moda tasarım / fashion designer."   (Sıraç, 10.09.2026)
  //
  // Kart bir gün önce "bu ne saçma mantıksız söz" diye kaldırılmıştı; şikâyet
  // uydurma aforizmalaraydı ("Sökmek ayıp değil; geç sökmek pahalı"). Bu yüzden
  // havuzdaki 47 özgün not UI dışına alındı ve yerine YALNIZCA atfı birincil
  // kaynaktan doğrulanmış tasarımcı sözleri kondu.
  //
  // Yöntem: 66 aday → her biri için bağımsız atıf denetimi (kaynak sayfası
  // açıldı, söz orada görüldü; alıntı-toplayıcı site ise elendi) → 62 geçti →
  // marka tonuna göre küratörlük (somut olan kalır: bir el hareketi, bir
  // malzeme, bir karar; nasihat ve aşınmış klişe elenir) → 43 söz.
  // Yazar başına en fazla 3 söz — havuz tek sese dönüşmesin.
  // Küratör bilerek ELEDİ: "moda geçer stil kalır" (YSL) tipi klişeler,
  // "elimde kalemle doğdum" (Lagerfeld) gibi mit cümleleri, ilham panosu dili.
  //
  // Bu kayıtların Türkçesi ÇEVİRİDİR (sourceType: translated_quote): özgün
  // metin quoteOriginal'da durur, sourceUrl açıldığında söz orada görülür.
  // -------------------------------------------------------------------------
  {
    id: "quote_101",
    weekIndex: 101,
    quoteTr: "Yıllardır düz bir etek yapmaya çalışıyorum. Doğru bir düz etek dünyanın en zor işi.",
    quoteOriginal: "For years I've been trying to make a straight skirt: making a straight skirt that's right now is the hardest thing in the world.",
    author: "Azzedine Alaïa",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "kalıp",
    sourceType: "translated_quote",
    sourceUrl: "https://www.anothermag.com/fashion-beauty/12395/a-conversation-with-azzedine-alaia-taking-time-rizzoli-book-donatien-grau",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_102",
    weekIndex: 102,
    quoteTr: "Atölyede yapılacak işi ben hazırlarım; herkesin masasına paketini bırakırım.",
    quoteOriginal: "I prepare what needs to be done in the workshop; I leave parcels on everyone's tables…",
    author: "Azzedine Alaïa",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "atölye",
    sourceType: "translated_quote",
    sourceUrl: "https://system-magazine.com/issues/issue-1/azzedine-alaia",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_103",
    weekIndex: 103,
    quoteTr: "Bir elbiseye bir yıl başlarım, on yıl sonra bitirdiğimi hissederim.",
    quoteOriginal: "I can start a dress one year and have the feeling of finishing it ten years later.",
    author: "Azzedine Alaïa",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "zaman",
    sourceType: "translated_quote",
    sourceUrl: "https://fondationazzedinealaia.org/en/heritage/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_104",
    weekIndex: 104,
    quoteTr: "Savile Row'da terziydim. Yumuşatmayı Givenchy'de öğrendim.",
    quoteOriginal: "Because I was a tailor, I didn't totally understand softness, or lightness. I learned lightness at Givenchy. I was a tailor at Savile Row. At Givenchy I learned to soften. For me, it was an education. As a designer I could have left it behind. But working at Givenchy helped me learn my craft.",
    author: "Alexander McQueen",
    authorRole: "Moda tasarımcısı, terzi",
    category: "fashion_design",
    theme: "öğrenme",
    sourceType: "translated_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/alexander-mcqueen-an-introduction",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_105",
    weekIndex: 105,
    quoteTr: "Yaptığım her şeyin temelinde terzilik var.",
    quoteOriginal: "Everything I do is based on tailoring",
    author: "Alexander McQueen",
    authorRole: "Moda tasarımcısı, terzi",
    category: "fashion_design",
    theme: "terzilik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/alexander-mcqueen-an-introduction",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_106",
    weekIndex: 106,
    quoteTr: "Sanayinin yöntemini geçmişin mirasıyla, el zanaatıyla karıştırmak isterim.",
    quoteOriginal: "I want always to mix the industrial way of doing things with the patrimonio of the past, with the artisanal tradition.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "miras",
    sourceType: "translated_quote",
    sourceUrl: "https://www.nssmag.com/en/fashion/22420/la-storia-di-prada-linea-rossa",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_107",
    weekIndex: 107,
    quoteTr: "Giyecek bir şey bulamadığım için moda yapmaya başladım.",
    quoteOriginal: "I started to make fashion because I couldn't find anything to wear. For years I kept on buying and wearing vintage, second hand and uniforms…any type of uniforms.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ihtiyaç",
    sourceType: "translated_quote",
    sourceUrl: "https://www.wmagazine.com/story/miuccia-prada-ugly-fashion",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_108",
    weekIndex: 108,
    quoteTr: "Bir imza kurup onu güncellemek: renk ya da kumaş değişsin, yeter.",
    quoteOriginal: "What I love is this idea of a wardrobe, the idea that we're establishing certain signatures and updating them, that a change in colour or fabric is enough.",
    author: "Phoebe Philo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "süreklilik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.nzherald.co.nz/lifestyle/phoebe-philo-leader-of-the-fashion-pack/HH55FVDJ4PZJRW2OHBVZVTZRYY/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_109",
    weekIndex: 109,
    quoteTr: "Hindistan'da üç bine yakın kişi bütün işlerimizi elle işliyor.",
    quoteOriginal: "We have nearly three thousand people in India who embroider all our things by hand.",
    author: "Dries Van Noten",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "işleme",
    sourceType: "translated_quote",
    sourceUrl: "https://the-talks.com/interview/dries-van-noten/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_110",
    weekIndex: 110,
    quoteTr: "Geçmişten hiç kullanılmamış canlı bir şey alırım; üstüne kendi fikrimi koyunca özgün olur.",
    quoteOriginal: "I take something from the past that has a sort of vitality that has never been exploited - like the crinoline - and get very intense. In the end, you do something original because you overlay your own ideas.",
    author: "Vivienne Westwood",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "geçmiş",
    sourceType: "translated_quote",
    sourceUrl: "https://collection.powerhouse.com.au/object/353280",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_111",
    weekIndex: 111,
    quoteTr: "Ceketi en sade haline indirdim: vatkayı ve astarı çıkardım, hafif kumaşa geçtim.",
    quoteOriginal: "I stripped the garment right back, taking out padding and linings, and employing the new, lighter-weight fabrics that had been developed.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "translated_quote",
    sourceUrl: "https://gulfnews.com/entertainment/giorgio-armani-in-conversation-with-gulf-news-1.1635256525391",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_112",
    weekIndex: 112,
    quoteTr: "Yenmiyorsa yemek değildir. Giyilmiyorsa moda değildir.",
    quoteOriginal: "If it's not edible, it's not food. If it's not wearable, it's not fashion.",
    author: "Alber Elbaz",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "giyilebilirlik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.dazeddigital.com/fashion/article/52602/1/on-the-power-of-kindness-alber-elbaz-in-his-own-words",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_113",
    weekIndex: 113,
    quoteTr: "Ustaca kesilmiş bir pamuklu pantolon, göz alıcı bir ipek elbiseden güzeldir.",
    quoteOriginal: "A pair of brilliantly cut cotton trousers can be more beautiful than a gorgeous silk gown.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kesim",
    sourceType: "translated_quote",
    sourceUrl: "https://the-talks.com/interview/yohji-yamamoto/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_114",
    weekIndex: 114,
    quoteTr: "Giysilerim en az on yıl giyilsin diye kumaşçıdan çok sağlam bir apre istedim.",
    quoteOriginal: "I wanted people to keep on wearing my clothes for at least 10 years or more, so I requested the fabric maker to make a very strong, tough finish.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dayanıklılık",
    sourceType: "translated_quote",
    sourceUrl: "https://the-talks.com/interview/yohji-yamamoto/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_115",
    weekIndex: 115,
    quoteTr: "Bu küçük, geleneksel Japon tekniklerini korumak benim derdim.",
    quoteOriginal: "It's my desire to protect these small, traditional Japanese techniques.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "gelenek",
    sourceType: "translated_quote",
    sourceUrl: "https://the-talks.com/interview/yohji-yamamoto/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_116",
    weekIndex: 116,
    quoteTr: "Onlar yırtık değil; kumaşa başka bir boyut veren açıklıklar. Bir tür dantel sayılır.",
    quoteOriginal: "To me they're not tears. Those are openings that give the fabric another dimension. The cutout might be considered another form of lace.",
    author: "Rei Kawakubo",
    authorRole: "Comme des Garçons kurucusu",
    category: "fashion_design",
    theme: "kumaş",
    sourceType: "translated_quote",
    sourceUrl: "https://artsandculture.google.com/story/rei-kawakubo-comme-des-gar%C3%A7ons-art-of-the-in-between-the-metropolitan-museum-of-art/cwVRRCff8h7zKA",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_117",
    weekIndex: 117,
    quoteTr: "Çocuksu, saf fırça darbelerini en resmi gece elbisesinin üstüne koymak istedim.",
    quoteOriginal: "I wanted to juxtapose the very naïve, almost childlike brushstrokes with the very formal evening dress.",
    author: "Rei Kawakubo",
    authorRole: "Comme des Garçons kurucusu",
    category: "fashion_design",
    theme: "karşıtlık",
    sourceType: "translated_quote",
    sourceUrl: "https://www.kci.or.jp/en/featured/comme-des-garcons/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_118",
    weekIndex: 118,
    quoteTr: "Modern, çalışan kadınlar için; hatlarıyla değil aklıyla çeken kadınlar için.",
    quoteOriginal: "They are for modern, working women. Women who do not need to assure their happiness by looking sexy to men, by emphasising their figures, but who attract them with their minds.",
    author: "Rei Kawakubo",
    authorRole: "Comme des Garçons kurucusu",
    category: "fashion_design",
    theme: "kimlik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.ngv.vic.gov.au/collecting-comme/rei-kawakubo-reframing-fashion/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_119",
    weekIndex: 119,
    quoteTr: "Bütün parçalarda biçime, kumaşı elde evirip çevirerek varmaya çalışıyoruz.",
    quoteOriginal: "For all of the garments, we try to reach the form by manipulating fabric.",
    author: "Junya Watanabe",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "biçim",
    sourceType: "translated_quote",
    sourceUrl: "https://system-magazine.com/issues/issue-20/in-the-words-of-junya-watanabe",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_120",
    weekIndex: 120,
    quoteTr: "Artık kalıbı kendim çıkarmıyorum ama kesimcilere verdiğim tarif kalıp bilgimden geliyor.",
    quoteOriginal: "While I no longer make patterns myself, the instructions I give to our cutters are based on my knowledge of pattern-making.",
    author: "Junya Watanabe",
    authorRole: "Moda tasarımcısı, kalıpçı",
    category: "fashion_design",
    theme: "kalıp",
    sourceType: "translated_quote",
    sourceUrl: "https://system-magazine.com/issues/issue-20/in-the-words-of-junya-watanabe",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_121",
    weekIndex: 121,
    quoteTr: "Vatkayı ve telayı kesilmemiş tek parça kumaşın içine gömebilir miyiz diye başladım.",
    quoteOriginal: "I started with the idea of whether we could make garments by embedding necessary structural parts such as shoulder padding and hair canvas, into an uncut piece of cloth to constitute garments.",
    author: "Junya Watanabe",
    authorRole: "Moda tasarımcısı, kalıpçı",
    category: "fashion_design",
    theme: "yapı",
    sourceType: "translated_quote",
    sourceUrl: "https://system-magazine.com/issues/issue-20/in-the-words-of-junya-watanabe",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_122",
    weekIndex: 122,
    quoteTr: "Parası olana giysi değil; kot ve tişört gibi, herkesin bildiği, kolay yıkanan şeyler istedim.",
    quoteOriginal: "What I wanted to make wasn't clothes that were only for people with money. It was things like jeans and T-shirts, things that were familiar to lots of people, easy to wash and easy to use.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "gündelik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.surfacemag.com/articles/issey-miyake-obituary/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_123",
    weekIndex: 123,
    quoteTr: "Param yoktu; Japonya'nın ucuz klasik kumaşlarını Paris bit pazarından bulduklarımla karıştırdım.",
    quoteOriginal: "When I started out I didn't have much money, so I mixed affordable classic textiles from Japan with pieces I found in the Paris flea markets.",
    author: "Kenzo Takada",
    authorRole: "Kenzo'nun kurucusu",
    category: "fashion_design",
    theme: "karışım",
    sourceType: "translated_quote",
    sourceUrl: "https://www.thegentlemansjournal.com/article/kenzo-takada-designer-interview/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_124",
    weekIndex: 124,
    quoteTr: "Benim formülüm şu: elbise yalnızca iyi kesildiği için güzeldir.",
    quoteOriginal: "Ma formule personnelle est celle de la robe qui est belle parce que seulement bien coupée.",
    author: "Madeleine Vionnet",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "kesim",
    sourceType: "translated_quote",
    sourceUrl: "https://gallica.bnf.fr/blog/21052021/madeleine-vionnet-architecte-du-tissu",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_125",
    weekIndex: 125,
    quoteTr: "Korsesiz bir bedene serbestçe dökülen kumaşın en uyumlu görüntü olduğunu kanıtladım.",
    quoteOriginal: "J'ai prouvé qu'un tissu qui tombait librement sur un corps sans cuirasse était le spectacle harmonieux par excellence.",
    author: "Madeleine Vionnet",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "beden",
    sourceType: "translated_quote",
    sourceUrl: "https://gallica.bnf.fr/blog/21052021/madeleine-vionnet-architecte-du-tissu",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_126",
    weekIndex: 126,
    quoteTr: "Elbiselerimin çoğu yalnızca kumaştan doğar.",
    quoteOriginal: "many a dress of mine is born of the fabric alone",
    author: "Christian Dior",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "kumaş",
    sourceType: "translated_quote",
    sourceUrl: "https://collections.vam.ac.uk/item/O15656/evening-dress-christian-dior-london/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_127",
    weekIndex: 127,
    quoteTr: "Çocukluk evim yumuşak pembe sıvalı, gri çakıllıydı; o iki renk hep benim renklerim kaldı.",
    quoteOriginal: "La maison d'enfance était crépie d'un rose très doux, mélangé avec du gravier gris, et ces deux couleurs sont demeurées en couture mes teintes de prédilection.",
    author: "Christian Dior",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "renk",
    sourceType: "translated_quote",
    sourceUrl: "https://www.galeriedior.com/histoire",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_128",
    weekIndex: 128,
    quoteTr: "İki küçük metal şişi tıkırdatıp bir şey üretmek bana hep sır kaldı.",
    quoteOriginal: "The art of holding and clicking those two little metal needles and making them produce something has always been a mystery to me, and indeed remains so.",
    author: "Elsa Schiaparelli",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "örgü",
    sourceType: "translated_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/shocking-life-by-elsa-schiaparelli",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_129",
    weekIndex: 129,
    quoteTr: "Kalıbın okunuşu, kumaşın beklenmedik tepkisi: en iyi usta bile küçük bir hayal kırıklığı bırakır.",
    quoteOriginal: "The interpretation of a dress, the means of making it, and the surprising way in which some materials react – all these factors, no matter how good an interpreter you have, invariably reserve a slight if not bitter disappointment for you.",
    author: "Elsa Schiaparelli",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "kusur",
    sourceType: "translated_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/shocking-life-by-elsa-schiaparelli",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_130",
    weekIndex: 130,
    quoteTr: "Heykeltıraş olmak istemiştim. Kumaşı işlemekle taşı işlemek benim için aynı şey.",
    quoteOriginal: "I wanted to be a sculptor. For me, working with fabric or stone is the same thing.",
    author: "Madame Grès",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "heykel",
    sourceType: "translated_quote",
    sourceUrl: "https://www.anothermag.com/art-photography/1007/madame-gres-couture-at-work",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_131",
    weekIndex: 131,
    quoteTr: "Malzemeyi elime alıp doğrudan onunla çalıştım; bildiğim tek şey heykeldi.",
    quoteOriginal: "C'est pour cette raison que j'ai pris le matériau et travaillé directement avec. J'ai utilisé les connaissances que j'avais, celles de la sculpture.",
    author: "Madame Grès",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "el",
    sourceType: "translated_quote",
    sourceUrl: "https://www.bourdelle.paris.fr/sites/default/files/2024-06/dp_gres_texte_bassdef.pdf",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_132",
    weekIndex: 132,
    quoteTr: "İşi kumaşın iplik yönü yapsın.",
    quoteOriginal: "Make the grain do the work.",
    author: "Charles James",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "kumaş",
    sourceType: "translated_quote",
    sourceUrl: "https://libmma.contentdm.oclc.org/digital/api/collection/p16028coll1/id/25200/download",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_133",
    weekIndex: 133,
    quoteTr: "Kalıp, dilde dilbilgisi gibidir; iyi tasarım tek bir cümledir, tek bir şey söyler.",
    quoteOriginal: "Cut in dressmaking is like grammar in a language. A good design should be like a well made sentence, and it should only express one idea at a time.",
    author: "Charles James",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "kalıp",
    sourceType: "translated_quote",
    sourceUrl: "https://libmma.contentdm.oclc.org/digital/api/collection/p16028coll1/id/25200/download",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_134",
    weekIndex: 134,
    quoteTr: "Tek bir dikişe on iki saat verdiğim oldu; o dikiş kendi yerini bulana kadar.",
    quoteOriginal: "I have sometimes spent twelve hours working on one seam; utterly entranced and not hungry or tired till finally it had as if of its own will found the precise place where it should be placed.",
    author: "Charles James",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "dikiş",
    sourceType: "translated_quote",
    sourceUrl: "https://libmma.contentdm.oclc.org/digital/api/collection/p16028coll1/id/25200/download",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_135",
    weekIndex: 135,
    quoteTr: "Bir elbiseyi baştan sona tek başına çizip kesen, kurup diken tek kişi Balenciaga'dır.",
    quoteOriginal: "Balenciaga alone is a couturier in the truest sense of the word. Only he is capable of cutting material, assembling a creation and sewing it by hand, the others are simply fashion designers.",
    author: "Coco Chanel",
    authorRole: "Couturier (Balenciaga hakkında)",
    category: "fashion_design",
    theme: "zanaat",
    sourceType: "translated_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/introducing-cristobal-balenciaga",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_136",
    weekIndex: 136,
    quoteTr: "Terzi; plan için mimar, biçim için heykeltıraş, renk için ressam olmalı.",
    quoteOriginal: "Un modisto debe ser arquitecto de la forma, pintor para el color, músico para la armonía y filósofo para la medida. (Müzenin İngilizce karşılığı: \"a couturier must be an architect for plans, a sculptor for shapes, an artist for colour, a musician for harmony and a philosopher for the sense of proportion.\")",
    author: "Cristóbal Balenciaga",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "translated_quote",
    sourceUrl: "https://www.cristobalbalenciagamuseoa.com/en/discover/cristobal-balenciaga/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 7,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_137",
    weekIndex: 137,
    quoteTr: "Kâğıtta zarif duran bir yaka baştan geçmeyebilir; zarif bir pantolon insanı sıkabilir.",
    quoteOriginal: "A collar that looks elegant on the drawing board might be difficult to pull over the head. And pants that appear elegant can be constricting.",
    author: "Sonia Rykiel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kullanım",
    sourceType: "translated_quote",
    sourceUrl: "https://asufidmmuseum.asu.edu/learn/articles/sonia-rykiel",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_138",
    weekIndex: 138,
    quoteTr: "Desenlerim düz asılı kalmayacaktı; kesilip yeniden bir araya getirilecekti.",
    quoteOriginal: "In learning to design for dress fabrics, I was involved in a special adventure, that of patterns which would not hang flat but would be cut and put together again in many different ways.",
    author: "Zandra Rhodes",
    authorRole: "Tekstil tasarımcısı",
    category: "fashion_design",
    theme: "desen",
    sourceType: "translated_quote",
    sourceUrl: "https://asufidmmuseum.asu.edu/learn/articles/zandra-rhodes-renaissance-gold",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_139",
    weekIndex: 139,
    quoteTr: "Dijital baskı yayılıyor; ben hâlâ şifonlarımı basan elek baskı atölyesini çalıştırıyorum.",
    quoteOriginal: "Screen printing is giving way to digital printing. I still run a screen printing workroom that has printed all my chiffons. I think it's very special and believe it to be one of the remaining left in London.",
    author: "Zandra Rhodes",
    authorRole: "Tekstil tasarımcısı",
    category: "fashion_design",
    theme: "baskı",
    sourceType: "translated_quote",
    sourceUrl: "https://www.stirworld.com/inspire-people-luminaries-of-our-times-zandra-rhodes",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_140",
    weekIndex: 140,
    quoteTr: "Bazen malzemeyi sen yönetirsin, bazen malzeme seni.",
    quoteOriginal: "Sometimes you're controlling the material, sometimes it's the other way around.",
    author: "Iris van Herpen",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "malzeme",
    sourceType: "translated_quote",
    sourceUrl: "https://monocle.com/fashion/iris-van-herpen-interview/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_141",
    weekIndex: 141,
    quoteTr: "Ülkemde zanaat kuşaklar boyu anneden kıza geçerdi; zamanla o bilginin çoğu kayboldu.",
    quoteOriginal: "In my country, many craft practices were passed down through generations, often from mothers to daughters. Over time, a lot of that knowledge disappeared.",
    author: "Maria Grazia Chiuri",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "aktarım",
    sourceType: "translated_quote",
    sourceUrl: "https://www.forbesindia.com/article/life/italy-has-lost-many-of-its-craft-traditions-india-must-not-maria-grazia-chiuri/2998029/1",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_142",
    weekIndex: 142,
    quoteTr: "İşlemeye kimsenin ihtiyacı yok; ama işleme kalıcı iş yaratıyor.",
    quoteOriginal: "Nobody needs embroideries, but it creates sustainable employment.",
    author: "Rahul Mishra",
    authorRole: "Couturier",
    category: "fashion_design",
    theme: "geçim",
    sourceType: "translated_quote",
    sourceUrl: "https://www.harpersbazaar.in/fashion/story/rahul-mishra-on-redefining-couture-through-craft-and-community-1093788-2024-09-16",
    usageRecommendation: "use_as_translation",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_143",
    weekIndex: 143,
    quoteTr: "İç yapıyı balen ve krinolin iskeletle kurduk; üstünü drape, pli, kat ve işlemeyle sardık.",
    quoteOriginal: "We sought to deliver the most perfect engineering for each garment, focusing on the understructure using stay and crinoline frames and enveloping it using various techniques like draping, pleating, layering and embroidery.",
    author: "Ayşe Ege",
    authorRole: "Moda tasarımcısı, Dice Kayek",
    category: "fashion_design",
    theme: "iskelet",
    sourceType: "translated_quote",
    sourceUrl: "https://www.wallpaper.com/fashion/east-meets-west-fashion-label-dice-kayek-wins-the-vas-jameel-prize-3",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
];

/**
 * Sol menüdeki "Haftanın Notu" kartı ÜÇ satır çizer (line-clamp-3, ~264px
 * sütun). Bundan uzun bir söz ekranda yarıda kesiliyor ve kart bozuk
 * görünüyordu — tasarımcı için "en ufak çizgi bile fark ettirir"
 * (bkz. feedback-control-equality). Uzunluk artık editoryal bir ölçüt:
 * karta sığmayan söz UI'ya çıkmaz.
 */
const CARD_MAX_CHARS = 108;

const APPROVED_RAW: WeeklyQuote[] = WEEKLY_QUOTES.filter(
  (q) => q.approvedForUi && q.quoteTr.length <= CARD_MAX_CHARS,
);

/**
 * Havuz dosyada yazara göre kümelenmiş duruyor (okunurluk için). Rotasyon o
 * sırayı olduğu gibi izleseydi aynı tasarımcı arka arkaya iki-üç hafta
 * çıkardı — kart "takıldı" gibi görünür. Burada yazarlar deterministik olarak
 * seyreltiliyor: en çok sözü olan yazardan başlanır, önce çift indisler sonra
 * tek indisler doldurulur. Bir yazarın payı toplamın yarısını geçmediği sürece
 * (havuzda tavan 3/47) bu yerleştirme iki komşu haftaya aynı yazarı DÜŞÜREMEZ.
 * Rastgelelik yok: aynı girdi hep aynı sırayı verir.
 */
function spreadByAuthor(quotes: WeeklyQuote[]): WeeklyQuote[] {
  const groups = new Map<string, WeeklyQuote[]>();
  for (const q of quotes) {
    const bucket = groups.get(q.author);
    if (bucket) bucket.push(q);
    else groups.set(q.author, [q]);
  }
  // Büyük gruplar önce; eşitlikte dosyadaki ilk görünme sırası korunur.
  const ordered = [...groups.values()]
    .map((bucket, firstSeen) => ({ bucket, firstSeen }))
    .sort((a, b) => b.bucket.length - a.bucket.length || a.firstSeen - b.firstSeen)
    .flatMap((entry) => entry.bucket);

  const out = new Array<WeeklyQuote>(ordered.length);
  let slot = 0;
  for (const quote of ordered) {
    out[slot] = quote;
    slot += 2;
    if (slot >= ordered.length) slot = 1;
  }
  return out;
}

/** UI'da gösterilmesi editoryal olarak onaylanmış sözler (yazarlar seyreltilmiş). */
export const APPROVED_WEEKLY_QUOTES: WeeklyQuote[] = spreadByAuthor(APPROVED_RAW);

/**
 * Deterministik haftalık söz seçimi.
 *
 * Sabit bir referans haftasından (epoch) itibaren geçen tam hafta sayısına göre
 * onaylı havuzdan modulo ile seçim yapar. Böylece:
 *   - aynı hafta boyunca herkes aynı sözü görür (random değil),
 *   - sayfa yenilendiğinde söz değişmez,
 *   - bir sonraki hafta deterministik olarak sıradaki söze geçilir,
 *   - havuz bitince başa döner.
 */
export function getWeeklyQuote(now: Date = new Date()): WeeklyQuote {
  const approved = APPROVED_WEEKLY_QUOTES;
  // Referans: 6 Temmuz 2026 Pazartesi (UTC gün başı).
  const epochStart = Date.UTC(2026, 6, 6);
  const current = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const msInWeek = 7 * 24 * 60 * 60 * 1000;
  const weeksPassed = Math.floor((current - epochStart) / msInWeek);
  const index = ((weeksPassed % approved.length) + approved.length) % approved.length;
  return approved[index];
}
