// Lospia / Aslı Filinta Operasyon — Haftanın Sözü havuzu.
//
// Filinta Metodolojisi'ne uygun, editoryal olarak filtrelenmiş 100 kayıtlık söz
// havuzu. Kaynak: Gemini Deep Research (bkz. gemini.md). Veri statik tutulur —
// production DB'ye migration YAPILMAZ; içerik yalnızca burada, typecheck ile
// korunan bir TypeScript sabiti olarak yaşar.
//
// Editoryal güvenlik katmanı (sourceConfidence / approvedForUi):
//   - "original" → Filinta Metodolojisi'nin kendi özgün atölye notları. Kesin
//                  tarihî atıf yapılmaz; "Atölye Notu" (tezgâh sesi) ve
//                  "Filinta Metodolojisi" (yöntem sesi) kolektif sesleri
//                  kullanılır. UI'da kullanılır.
//   - "high"     → resmî marka / müze / vakıf / akademik yayın kaynaklı doğrulanmış
//                  sözler, UI'da kullanılır (approvedForUi: true).
//   - "medium"   → Wikipedia/Wikiquote, dergi/haber ve kesin atfı doğrulanamayan
//                  tarihî sözler. İlk aşamada UI dışında (approvedForUi: false).
//   - "low"      → quote-aggregator / blog kaynaklı, doğrulaması zayıf sözler.
//                  UI dışında (approvedForUi: false).
//
// TON KURALI (AF_MD marka dosyası, 2026-08-29): özgün notlar bir işi TARİF
// eder, kimseye nasihat etmez. Somut olan yazılır — bir el hareketi, bir
// malzeme, bir sıra, bir sayı. Soyut sıfat yığını ("kadim", "zamansız",
// "eşsiz", "sessiz imza", "ruh", "pusula", "köprü") ve motivasyon cümlesi
// ("her sabah üzerine titre") YASAK. Cümle kısa; Türkçenin kendi ritmiyle
// yazılır, İngilizceden çevrilmez. Marka dosyasındaki doğrulanmış sayı, yer
// ve proje adları (kooperatif isimleri, adetler, yıllar) bu havuza GİRMEZ —
// buradan yalnızca ton ve mantık alınır.
//
// UI yalnızca APPROVED_WEEKLY_QUOTES üzerinden döner; söz seçimi deterministiktir
// (haftalık rotasyon), random DEĞİLDİR.

export type WeeklyQuote = {
  id: string;
  weekIndex: number;
  quoteTr: string;
  quoteOriginal?: string | null;
  author: string;
  authorRole: string;
  category: string;
  theme: string;
  sourceType:
    | "verified_quote"
    | "public_domain_quote"
    | "translated_quote"
    | "inspired_original";
  sourceUrl?: string | null;
  usageRecommendation: "use" | "use_as_translation" | "use_as_inspired";
  brandFitScore: number;
  uiDisplaySuggestion: string;
  sourceConfidence: "high" | "medium" | "low" | "original";
  approvedForUi: boolean;
};

export const WEEKLY_QUOTES: WeeklyQuote[] = [
  {
    id: "quote_001",
    weekIndex: 1,
    quoteTr: "Sadelik, tüm gerçek zarafetin anahtarıdır.",
    quoteOriginal: "Simplicity is the keynote of all true elegance.",
    author: "Coco Chanel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "zarafet",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Coco_Chanel",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_002",
    weekIndex: 2,
    quoteTr: "Moda mimaridir; her şey oranlarla ilgilidir.",
    quoteOriginal: "Fashion is architecture: it is a matter of proportions.",
    author: "Coco Chanel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Coco_Chanel",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_003",
    weekIndex: 3,
    quoteTr: "Çok çalışmak her zaman benim tek kurtuluşum oldu.",
    quoteOriginal: "Hard work has always been my salvation.",
    author: "Coco Chanel",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "emek",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Coco_Chanel",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_004",
    weekIndex: 4,
    quoteTr: "Detaylar en az esas olan kadar önemlidir. Yetersiz kaldıklarında tüm tasarımı yok ederler.",
    quoteOriginal: "The detail is as important as the essential is. When it is inadequate, it destroys the whole outfit.",
    author: "Christian Dior",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://www.pairfum.com/christian-dior-his-50-x-most-memorable-quotes/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_005",
    weekIndex: 5,
    quoteTr: "Makinelerin çağında dikişçilik, insani, kişisel ve taklit edilemez olanın son sığınaklarından biridir.",
    quoteOriginal: "In a machine age, dressmaking is one of the last refuges of the human, the personal, the inimitable.",
    author: "Christian Dior",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Christian_Dior",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_006",
    weekIndex: 6,
    quoteTr: "Robert Piguet bana gerçek zarafetin kaynağı olan sadeliğin erdemlerini öğretti.",
    quoteOriginal: "Robert Piguet taught me the virtues of simplicity through which true elegance must come.",
    author: "Christian Dior",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Christian_Dior",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_007",
    weekIndex: 7,
    quoteTr: "Moda geçer, stil kalıcıdır.",
    quoteOriginal: "Fashions fade, style is eternal.",
    author: "Yves Saint Laurent",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "miras",
    sourceType: "verified_quote",
    sourceUrl: "https://museeyslparis.com/en/biography/premier-smoking",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_008",
    weekIndex: 8,
    quoteTr: "Kendimi kadınların hizmetine sunmak, geçen yüzyıldaki büyük özgürleşme hareketlerinde onlara eşlik etmek istedim.",
    quoteOriginal: "I wanted to put myself at the service of women. To accompany them in the great movement for liberation.",
    author: "Yves Saint Laurent",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kadın emeği",
    sourceType: "translated_quote",
    sourceUrl: "https://gloss-newyork.com/fashion-ready-to-wear/saint-laurent/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_009",
    weekIndex: 9,
    quoteTr: "Kuralları yıkmak için önce onlara hâkim olmalısınız. Buradayım; kuralları yıkmak ama geleneği korumak için.",
    quoteOriginal: "You've got to know the rules to break them. That's what I'm here for, to demolish the rules but to keep the tradition.",
    author: "Alexander McQueen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://www.vam.ac.uk/articles/alexander-mcqueen-an-introduction",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_010",
    weekIndex: 10,
    quoteTr: "Moda bir kaçış ve özgürleşme alanı olmalıdır, bir hapishane değil.",
    quoteOriginal: "Fashion should be a form of escapism, and not a form of imprisonment.",
    author: "Alexander McQueen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://www.hockerty.com/en-us/blog/fashion-quotes-men",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_011",
    weekIndex: 11,
    quoteTr: "Daha az satın alın, iyi seçin, kalıcı kılın.",
    quoteOriginal: "Buy less, choose well, make it last.",
    author: "Vivienne Westwood",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.viviennewestwood.com/sustainability/make-it-last.html",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_012",
    weekIndex: 12,
    quoteTr: "Sadece moda yapmak istemedim, tasarımlarım aracılığıyla bir hikaye anlatmak istedim.",
    quoteOriginal: "I didn't want to just do fashion, I wanted to tell a story through my designs.",
    author: "Vivienne Westwood",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "miras",
    sourceType: "translated_quote",
    sourceUrl: "https://www.designville.eu/blog/buy-less-choose-well-thank-you-vivienne-westwood",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_013",
    weekIndex: 13,
    quoteTr: "Zarafet göze batmak değil, akılda kalmaktır.",
    quoteOriginal: "Elegance is not standing out, but being remembered.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "zarafet",
    sourceType: "verified_quote",
    sourceUrl: "https://www.standard.co.uk/lifestyle/fashion/giorgio-armani-dies-obituary-life-of-legendary-italian-designer-b1246059.html",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_014",
    weekIndex: 14,
    quoteTr: "Alanınızda en iyisi olmak büyük bir hırstır; disiplin ve muazzam miktarda çaba gerektirir.",
    quoteOriginal: "To be the best in your field is a great ambition, and requires discipline and a huge amount of effort.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://www.azquotes.com/author/529-Giorgio_Armani?p=3",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_015",
    weekIndex: 15,
    quoteTr: "Ben tablodaki bir kadını değil; yaşayan, üreten ve çalışan kadını giydirmek istedim.",
    quoteOriginal: "I wanted to dress the woman who lives and works, not the woman in a painting.",
    author: "Giorgio Armani",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kadın emeği",
    sourceType: "verified_quote",
    sourceUrl: "https://www.azquotes.com/author/529-Giorgio_Armani?p=3",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_016",
    weekIndex: 16,
    quoteTr: "Yaratım ile iş dünyası arasında fark yoktur. Bir şirketin işleyişi de yaratıcı, yenilikçi ve dönüştürücü olmalıdır.",
    quoteOriginal: "There is no difference between creation and business. The business aspect of a company has to be creative, innovative, transformative.",
    author: "Rei Kawakubo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://successstory.com/inspiration/successstory-quotes-rei-kawakubo-part-01",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_017",
    weekIndex: 17,
    quoteTr: "Yaratıcılık her şeyi ileriye taşır. Yeni bir şey olmadan ilerleme olmaz. Yaratım, yeniliktir.",
    quoteOriginal: "Creation takes things forward. Without anything new, there is no progress. Creation equals new.",
    author: "Rei Kawakubo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/quote/1647328/Rei-Kawakubo-Creation-takes-things-forward-Without-anything-new-there-is-no-progress",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_018",
    weekIndex: 18,
    quoteTr: "Çünkü temel insani mesele, insanların değişimden korkmasıdır.",
    quoteOriginal: "Because the fundamental human problem is that people are afraid of change.",
    author: "Rei Kawakubo",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/rei-kawakubo-quotes",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_019",
    weekIndex: 19,
    quoteTr: "Tasarım soyut bir felsefe için değil, doğrudan yaşam içindir.",
    quoteOriginal: "Design is not for philosophy, it's for life.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Issey_Miyake",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_020",
    weekIndex: 20,
    quoteTr: "En çok insan formuyla ilgileniyorum. Giysi, yaşayan insana en yakın olan şeydir.",
    quoteOriginal: "I am most interested in people and the human form. Clothing is closest to all humans.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Issey_Miyake",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_021",
    weekIndex: 21,
    quoteTr: "Beni ilgilendiren kumaşın teknolojisi, her şeye sıfırdan ve malzemeden başlamaktır.",
    quoteOriginal: "The technology of fabrics is what interests me. Making things from scratch.",
    author: "Issey Miyake",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Issey_Miyake",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_022",
    weekIndex: 22,
    quoteTr: "Benim için moda, bedene en yakın sanat formudur. Kim olduğumuzun en yalın ifadesidir.",
    quoteOriginal: "For me, fashion is an art form that is very close to the body. It is the closest expression of who we are.",
    author: "Iris van Herpen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Iris_van_Herpen",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_023",
    weekIndex: 23,
    quoteTr: "El işçiliği ve dijital zanaatkarlık yan yana var olabilir, birbirini besleyebilir; ayrılmamalıdırlar.",
    quoteOriginal: "Handmaking and digital craftsmanship can coexist and feed each other. They shouldn't be separated.",
    author: "Iris van Herpen",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Iris_van_Herpen",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_024",
    weekIndex: 24,
    quoteTr: "Elleriniz kültürdür. Ruhunuz parmak uçlarınızdan dışarı süzülür. Moda, zanaatkarlığın son kalesidir.",
    quoteOriginal: "Your hands are culture. Your soul comes out at the tips of your fingers. Fashion is the last business of craftsmanship.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://www.sleek-mag.com/article/notes-and-quotes-from-yohji-yamamoto/",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_025",
    weekIndex: 25,
    quoteTr: "Kusursuzluğun çirkin olduğunu düşünüyorum. İnsan elinden çıkan şeylerde izler, hatalar ve düzensizlikler görmek isterim.",
    quoteOriginal: "I think perfection is ugly. Somewhere in the things humans make, I want to see scars, failure, disorder, distortion.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "emek",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikiquote.org/wiki/Yohji_Yamamoto",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_026",
    weekIndex: 26,
    quoteTr: "Lütfen giysileri israf etmeyin! Tasarımla bir aşk macerası yaşayın ve o giysiyle birlikte uzun yıllar yaşayın.",
    quoteOriginal: "Please, don't waste clothing! Fall in love and live with this piece of clothing.",
    author: "Yohji Yamamoto",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.sleek-mag.com/article/notes-and-quotes-from-yohji-yamamoto/",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_027",
    weekIndex: 27,
    quoteTr: "Ben kadın olmaktan gurur duyan, kadınlığını yaşayan tüm güçlü kadınlar için tasarlıyorum.",
    quoteOriginal: "I design for the woman who loves being a woman.",
    author: "Diane von Furstenberg",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "kadın emeği",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Diane_von_Furstenberg",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_028",
    weekIndex: 28,
    quoteTr: "Hedefim sade, rahat ve zarif bir elbise yaratmaktı; kadının kendi gücünü ortaya çıkaran bir tasarım.",
    quoteOriginal: "My goal was to create a dress that was simple, comfortable, and elegant.",
    author: "Diane von Furstenberg",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sadelik",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Diane_von_Furstenberg",
    usageRecommendation: "use_as_translation",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_029",
    weekIndex: 29,
    quoteTr: "Bir tasarımcı olarak yapabileceğiniz en sürdürülebilir şey, insanların atmak istemeyeceği, kalıcı parçalar üretmektir.",
    quoteOriginal: "One of the most sustainable things you can do as a designer is to create pieces that people want and won't want to throw away.",
    author: "Stella McCartney",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.stellamccartney.com/on/demandware.static/-/Library-Sites-StellaMcCartneySharedLibrary/default/dwce449f0d/report/EcoImpact_2021_CM_FINAL.pdf",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_030",
    weekIndex: 30,
    quoteTr: "İnsan olarak kurduğumuz her tekil etkileşimin ve aldığımız her kararın gezegen üzerinde bir etkisi vardır.",
    quoteOriginal: "Every single interaction that we have as humans can have an impact on the planet.",
    author: "Stella McCartney",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.dezeen.com/2018/07/10/stella-mccartney-interview-sustainable-design/",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_031",
    weekIndex: 31,
    quoteTr: "Sürdürülebilir moda bir akım değil, hepimizin üstlenmesi gereken bir sorumluluktur.",
    quoteOriginal: "Sustainable fashion is not a trend, it's a responsibility.",
    author: "Stella McCartney",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://ecoswap.uk/top-10-sustainable-fashion-quotes/",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_032",
    weekIndex: 32,
    quoteTr: "Bir şeyi derinlemesine yapabilmenin tek yolu çok çalışmaktır.",
    quoteOriginal: "The only way to do something in depth is to work hard.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/miuccia-prada-quotes",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_033",
    weekIndex: 33,
    quoteTr: "Ben gerçekten uzun ömürlü olacak, zamanın ötesinde ve kalıcı giysiler yapmak istiyorum.",
    quoteOriginal: "I really want to make clothes that will last a long time.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "sürdürülebilirlik",
    sourceType: "translated_quote",
    sourceUrl: "https://www.bookey.app/quote-author/miuccia-prada",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_034",
    weekIndex: 34,
    quoteTr: "Ne giydiğiniz, kendinizi dünyaya nasıl sunduğunuzdur. Özellikle bugün, iletişim bu kadar hızlıyken; moda anlık bir dildir.",
    quoteOriginal: "What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language.",
    author: "Miuccia Prada",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "zarafet",
    sourceType: "verified_quote",
    sourceUrl: "https://quotefancy.com/miuccia-prada-quotes",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "low",
    approvedForUi: false,
  },
  {
    id: "quote_035",
    weekIndex: 35,
    quoteTr: "Tasarım; konfor ile lüksü, pratik olan ile arzulananı dengeleme mücadelesidir.",
    quoteOriginal: "Design is a constant challenge to balance comfort with luxe, the practical with the desirable.",
    author: "Donna Karan",
    authorRole: "Moda tasarımcısı",
    category: "fashion_design",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Donna_Karan",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Tasarımcıdan Not",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_036",
    weekIndex: 36,
    quoteTr: "Hayatınızda yararlı olduğunu bilmediğiniz ya da güzel olduğuna inanmadığınız hiçbir şeye yer vermeyin.",
    quoteOriginal: "Have nothing in your houses that you do not know to be useful or believe to be beautiful.",
    author: "William Morris",
    authorRole: "Tasarımcı ve zanaat kuramcısı",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/William_Morris",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_037",
    weekIndex: 37,
    quoteTr: "Güzel bir el işçiliği, mutlu bir kalbin ve disiplinli bir zihnin doğal ifadesidir.",
    quoteOriginal: "Beautiful handwork is the natural expression of a joyful heart and a disciplined mind.",
    author: "William Morris",
    authorRole: "Tasarımcı ve zanaat kuramcısı",
    category: "craft",
    theme: "emek",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/William_Morris",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_038",
    weekIndex: 38,
    quoteTr: "Daha az, ama daha iyi.",
    quoteOriginal: "Weniger, aber besser",
    author: "Dieter Rams",
    authorRole: "Endüstriyel tasarımcı",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Dieter_Rams",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_039",
    weekIndex: 39,
    quoteTr: "İyi tasarım son detayına kadar titizdir. Süreçteki özen ve doğruluk, insana duyulan saygının göstergesidir.",
    quoteOriginal: "Good design is thorough down to the last detail. Care and accuracy in the design process show respect towards the consumer.",
    author: "Dieter Rams",
    authorRole: "Endüstriyel tasarımcı",
    category: "craft",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://designmuseum.org/discover-design/all-stories/what-is-good-design-a-quick-look-at-dieter-rams-ten-principles",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_040",
    weekIndex: 40,
    quoteTr: "İyi tasarım çevre dostudur. Tasarım, ürünün yaşam döngüsü boyunca kaynakları korumaya ve kirliliği azaltmaya hizmet etmelidir.",
    quoteOriginal: "Good design is environmentally friendly. Design makes an important contribution to the preservation of the environment.",
    author: "Dieter Rams",
    authorRole: "Endüstriyel tasarımcı",
    category: "craft",
    theme: "sürdürülebilirlik",
    sourceType: "verified_quote",
    sourceUrl: "https://designmuseum.org/discover-design/all-stories/what-is-good-design-a-quick-look-at-dieter-rams-ten-principles",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_041",
    weekIndex: 41,
    quoteTr: "Detaylar sadece detay değildir; tasarımı oluşturan şeyin ta kendisidir.",
    quoteOriginal: "The details are not the details. They make the design.",
    author: "Charles Eames",
    authorRole: "Tasarımcı ve mimar",
    category: "craft",
    theme: "operasyon disiplini",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Charles_and_Ray_Eames",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_042",
    weekIndex: 42,
    quoteTr: "Tasarım, unsurları belirli bir amaca en iyi hizmet edecek şekilde düzenleme planıdır.",
    quoteOriginal: "Design is a plan for arranging elements in such a way as best to accomplish a particular purpose.",
    author: "Charles Eames",
    authorRole: "Tasarımcı ve mimar",
    category: "craft",
    theme: "disiplin",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Charles_and_Ray_Eames",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_043",
    weekIndex: 43,
    quoteTr: "İşlevsel olan, sadece iyi görünenden daha iyidir. Görünüm değişebilir ama işleyen şey her zaman işler.",
    quoteOriginal: "What works is better than what looks good. The looks good can change, but what works works.",
    author: "Ray Eames",
    authorRole: "Tasarımcı ve sanatçı",
    category: "craft",
    theme: "operasyon disiplini",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Charles_and_Ray_Eames",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_044",
    weekIndex: 44,
    quoteTr: "Karışık hale getirmek kolaydır, basitleştirmek zordur. Herkes karmaşıklaştırabilir, sadece az sayıda kişi basitleştirebilir.",
    quoteOriginal: "To complicate is easy, to simplify is difficult... Everyone is able to complicate. Few are able to simplify.",
    author: "Bruno Munari",
    authorRole: "Tasarımcı ve yazar",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Bruno_Munari",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_045",
    weekIndex: 45,
    quoteTr: "Nesneler özenle ve akılla yapıldığında, güzellikleri doğrudan işlevselliklerinden dışarı sızar.",
    quoteOriginal: "When objects are made with care and intelligence, their beauty shines through their functionality.",
    author: "Bruno Munari",
    authorRole: "Tasarımcı ve yazar",
    category: "craft",
    theme: "estetik",
    sourceType: "translated_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Bruno_Munari",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_046",
    weekIndex: 46,
    quoteTr: "Bir parçayı tarif ederken sıfat kullanmayız: ölçü, renk, malzeme. Gerisi lafta kalır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sadelik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_047",
    weekIndex: 47,
    quoteTr: "Çizgi, yürüyüşe çıkmış bir noktadır.",
    quoteOriginal: "A line is a dot that went for a walk.",
    author: "Paul Klee",
    authorRole: "Ressam ve Bauhaus kuramcısı",
    category: "craft",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Paul_Klee",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_048",
    weekIndex: 48,
    quoteTr: "Sanat görüneni yeniden üretmez; aksine, insan gözü için onu görünür kılar.",
    quoteOriginal: "Art does not reproduce the visible; rather, it makes visible.",
    author: "Paul Klee",
    authorRole: "Ressam ve Bauhaus kuramcısı",
    category: "craft",
    theme: "estetik",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Paul_Klee",
    usageRecommendation: "use",
    brandFitScore: 8,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_049",
    weekIndex: 49,
    quoteTr: "Sanatın herhangi bir dalında kendi dünyanı yaratabilmek, her şeyden önce cesaret gerektirir.",
    quoteOriginal: "To create one's world in any of the arts takes courage.",
    author: "Georgia O'Keeffe",
    authorRole: "Modernist ressam",
    category: "craft",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://en.wikipedia.org/wiki/Georgia_O%27Keeffe",
    usageRecommendation: "use",
    brandFitScore: 9,
    uiDisplaySuggestion: "Ustalık Notu",
    sourceConfidence: "medium",
    approvedForUi: false,
  },
  {
    id: "quote_050",
    weekIndex: 50,
    quoteTr: "Malzeme bir iletişim aracıdır. Ona hükmetmek yerine onu dinlemek bizi gerçekten aktif ve yaratıcı kılar.",
    quoteOriginal: "The material is a means of communication. Listening to it, not dominating it, makes us truly active.",
    author: "Anni Albers",
    authorRole: "Tekstil ve dokuma sanatçısı",
    category: "craft",
    theme: "ustalık",
    sourceType: "verified_quote",
    sourceUrl: "https://www.albersfoundation.org/alberses/teaching/anni-albers/material-as-metaphor",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_051",
    weekIndex: 51,
    quoteTr: "Yaparım, bozarım, yeniden yaparım. Bu döngü, zanaatın ve zihnin kendini iyileştirme biçimidir.",
    quoteOriginal: "I do, I undo, I redo. This is the process of making and repairing.",
    author: "Louise Bourgeois",
    authorRole: "Heykeltıraş ve sanatçı",
    category: "craft",
    theme: "dönüşüm",
    sourceType: "verified_quote",
    sourceUrl: "https://www.euppublishing.com/doi/10.3366/jobs.2023.0389",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_052",
    weekIndex: 52,
    quoteTr: "İplik; zamanın akışını, dokuyan bir annenin dikişini, bağların hassasiyetini ve hafızaya tutunmayı temsil eder.",
    quoteOriginal: "The thread represents the unspooling of time, the sewing of the mother-weaver, the fragility of relationships and linkage to memory.",
    author: "Louise Bourgeois",
    authorRole: "Heykeltıraş ve sanatçı",
    category: "craft",
    theme: "miras",
    sourceType: "translated_quote",
    sourceUrl: "https://sculpture.org/blogpost/1860273/350131/Louise-Bourgeois-Conscious-and-Unconscious",
    usageRecommendation: "use_as_translation",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: false,
  },
  {
    id: "quote_053",
    weekIndex: 53,
    quoteTr: "Ölçüyü iki kez alırız, kumaşı bir kez keseriz.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_054",
    weekIndex: 54,
    quoteTr: "Vicdanlı bir tasarımcı bizzat tasarlamaz; aksine, nesneye kendi kendini var etme ve tasarlama şansı verir.",
    quoteOriginal: "The conscientious designer does not himself design at all but rather give the object-to-be a chance to design itself.",
    author: "Anni Albers",
    authorRole: "Tekstil ve dokuma sanatçısı",
    category: "craft",
    theme: "sadelik",
    sourceType: "verified_quote",
    sourceUrl: "https://www.tate.org.uk/whats-on/tate-modern/anni-albers/seven-life-hacks-anni-albers",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: false,
  },
  {
    id: "quote_055",
    weekIndex: 55,
    quoteTr: "Yavaşlık ve deneysellik, zanaatta gerçek yeniliğin ve kalıcı kalitenin en sağlam temelleridir.",
    quoteOriginal: "Slowness and experimentation are the foundations of true innovation and lasting quality in craft.",
    author: "Anni Albers",
    authorRole: "Tekstil ve dokuma sanatçısı",
    category: "craft",
    theme: "sabır",
    sourceType: "translated_quote",
    sourceUrl: "https://www.tate.org.uk/whats-on/tate-modern/anni-albers/seven-life-hacks-anni-albers",
    usageRecommendation: "use",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "high",
    approvedForUi: true,
  },
  {
    id: "quote_056",
    weekIndex: 56,
    quoteTr: "Sökmek ayıp değil; geç sökmek pahalı.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_057",
    weekIndex: 57,
    quoteTr: "El işinde hız yoktur, tekrar vardır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_058",
    weekIndex: 58,
    quoteTr: "Bir parçanın fiyatı kumaşta değil, ona harcanan günde belli olur.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_059",
    weekIndex: 59,
    quoteTr: "Zor olan dikmek değil; ikinci parçayı birincisiyle aynı dikmek.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_060",
    weekIndex: 60,
    quoteTr: "Kayıt tutulmayan iş yapılmamış sayılır. Kim, ne, ne zaman — üç satır yeter.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_061",
    weekIndex: 61,
    quoteTr: "Ustaya sorulan soru, iki gün sonra sökülen dikişten kısadır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_062",
    weekIndex: 62,
    quoteTr: "İşi bölüşmek, sorumluluğu bölmek değildir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_063",
    weekIndex: 63,
    quoteTr: "Bir işi üç cümlede anlatamıyorsak, iş daha netleşmemiştir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sadelik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_064",
    weekIndex: 64,
    quoteTr: "Fikir tezgâha inmediyse hâlâ fikirdir.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_065",
    weekIndex: 65,
    quoteTr: "İlmek atılmadan önce düşünülür, atıldıktan sonra sökülür.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_066",
    weekIndex: 66,
    quoteTr: "Numune onaylanmadan kesim başlamaz; sıra bozulunca iş değil kumaş gider.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_067",
    weekIndex: 67,
    quoteTr: "Yeni bir teknik bir günde öğrenilir, her gün tekrar edilerek elde kalır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_068",
    weekIndex: 68,
    quoteTr: "Yarım bırakılan iş, bir dahaki sefere baştan başlar.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_069",
    weekIndex: 69,
    quoteTr: "Astarın içi dışı kadar temiz olur. Kimse görmüyor diye başka türlü dikilmez.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_070",
    weekIndex: 70,
    quoteTr: "Gün sonunda tezgâh toplanır; ertesi sabah dağınıklıktan başlamak işten çalar.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "disiplin",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_071",
    weekIndex: 71,
    quoteTr: "Elde iş varken yeni iş almak ikisini de geciktirir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_072",
    weekIndex: 72,
    quoteTr: "Son ütü, ilk dikişi görünür kılar.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "estetik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 9,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_073",
    weekIndex: 73,
    quoteTr: "Tarih tahmin değildir. Tahminse öyle söylenir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "disiplin",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_074",
    weekIndex: 74,
    quoteTr: "Bir işin sahibi varsa iş yürür. Herkesin işi kimsenin işidir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_075",
    weekIndex: 75,
    quoteTr: "Kâğıtta denenmeyen kalıp kumaşta denenir; kumaş geri gelmez.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_076",
    weekIndex: 76,
    quoteTr: "Bir teknik, onu gösterecek biri kaldığı sürece yaşar.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "miras",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_077",
    weekIndex: 77,
    quoteTr: "Bir parçanın kaç kişinin elinden geçtiğini bilmeden fiyatını konuşmayız.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "kadın emeği",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_078",
    weekIndex: 78,
    quoteTr: "Ne kadar sade görünüyorsa, o kadar çok kez sökülmüştür.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "zarafet",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_079",
    weekIndex: 79,
    quoteTr: "Kumaş biterse o parça biter. Az üretmek eksiklik değil, karar.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_080",
    weekIndex: 80,
    quoteTr: "İlk parça yavaş çıkar. Yavaş çıkmazsa ikincisi hiç çıkmaz.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_081",
    weekIndex: 81,
    quoteTr: "Artan kumaş çöp değil, bir sonraki parçanın başlangıcıdır.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_082",
    weekIndex: 82,
    quoteTr: "Ustalık, hangi dikişin sökülmesi gerektiğini ilk bakışta görmektir.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_083",
    weekIndex: 83,
    quoteTr: "Bir işi devrederken elindeki her şeyi devret; yarısı sende kalırsa iş de sende kalır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "kadın emeği",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_084",
    weekIndex: 84,
    quoteTr: "İki kişi aynı işi yapıyorsa biri boşa çalışıyor. Sabah on dakika bunu çözer.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_085",
    weekIndex: 85,
    quoteTr: "Elimizde ne varsa onunla başlarız; olmayanı beklemek üretim değil, erteleme.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_086",
    weekIndex: 86,
    quoteTr: "Sabah listesi üç satırdır: ismi, işi, tarihi.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sadelik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_087",
    weekIndex: 87,
    quoteTr: "Bir dikiş sökülüyorsa suçlusu aranmaz, sebebi yazılır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "emek",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_088",
    weekIndex: 88,
    quoteTr: "Desen bir yerden geliyorsa, o yerin adı da beraber yazılır.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "miras",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_089",
    weekIndex: 89,
    quoteTr: "Karar çıkmayan toplantı ertesi hafta yeniden yapılır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_090",
    weekIndex: 90,
    quoteTr: "Renk kartına güneşte de bakarız; masa lambası herkesi yanıltır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "estetik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_091",
    weekIndex: 91,
    quoteTr: "Eskiyen parça atılmaz, sökülür. Sökülen her parça bir sonrakine ölçü verir.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "dönüşüm",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_092",
    weekIndex: 92,
    quoteTr: "Bir tarih değişiyorsa sebebiyle birlikte yazılır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "disiplin",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_093",
    weekIndex: 93,
    quoteTr: "Kumaşa istediğimizi değil, kaldırdığını yaptırırız.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_094",
    weekIndex: 94,
    quoteTr: "Provada görülen, üretimde görülecek olandır. Provayı atlamak işi iki kez yapmaktır.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sabır",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_095",
    weekIndex: 95,
    quoteTr: "Öğrenilen teknik anlatılmazsa bizde kalır; bizde kalan teknik biter.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "miras",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_096",
    weekIndex: 96,
    quoteTr: "Elin bildiği kâğıda geçmezse, tezgâh boşaldığında o bilgi de gider.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "kadın emeği",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_097",
    weekIndex: 97,
    quoteTr: "Numuneye elle dokunmadan onay verilmez; ekranda kumaşın tuşesi yok.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "ustalık",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_098",
    weekIndex: 98,
    quoteTr: "Bir işe başlamadan sonunu yazarız: kaç el, kaç gün, ne kadar kumaş.",
    quoteOriginal: null,
    author: "Atölye Notu",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "operasyon disiplini",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "Atölye Notu",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_099",
    weekIndex: 99,
    quoteTr: "İyi iş, ertesi sabah utanmadan bakabildiğin iştir.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "zarafet",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
  {
    id: "quote_100",
    weekIndex: 100,
    quoteTr: "Yeni bir şey almadan önce elimizdekine bakarız; cevap çoğu zaman oradadır.",
    quoteOriginal: null,
    author: "Filinta Metodolojisi",
    authorRole: "FM özgün notu",
    category: "fm_original",
    theme: "sürdürülebilirlik",
    sourceType: "inspired_original",
    sourceUrl: null,
    usageRecommendation: "use_as_inspired",
    brandFitScore: 10,
    uiDisplaySuggestion: "FM Haftalık İlham",
    sourceConfidence: "original",
    approvedForUi: true,
  },
];

/** UI'da gösterilmesi editoryal olarak onaylanmış sözler. */
export const APPROVED_WEEKLY_QUOTES: WeeklyQuote[] = WEEKLY_QUOTES.filter(
  (q) => q.approvedForUi,
);

/**
 * Deterministik haftalık söz seçimi.
 *
 * Sabit bir referans haftasından (epoch) itibaren geçen tam hafta sayısına göre
 * onaylı havuzdan modulo ile seçim yapar. Böylece:
 *   - aynı hafta boyunca herkes aynı sözü görür (random değil),
 *   - sayfa yenilendiğinde söz değişmez,
 *   - bir sonraki hafta deterministik olarak sıradaki söze geçilir,
 *   - havuz bitince başa döner.
 */
export function getWeeklyQuote(now: Date = new Date()): WeeklyQuote {
  const approved = APPROVED_WEEKLY_QUOTES;
  // Referans: 6 Temmuz 2026 Pazartesi (UTC gün başı).
  const epochStart = Date.UTC(2026, 6, 6);
  const current = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const msInWeek = 7 * 24 * 60 * 60 * 1000;
  const weeksPassed = Math.floor((current - epochStart) / msInWeek);
  const index = ((weeksPassed % approved.length) + approved.length) % approved.length;
  return approved[index];
}
